# _config.yml

remote_theme: pages-themes/minimal

title: "Il Tuo Sito"
description: "Descrizione del tuo sito"
url: "https://il-tuo-sito.com"

plugins:
  - jekyll-feed

# Altre impostazioni specifiche del tuo sito
# ...
